export const chart_data = {
    "https://atlas.immobilienscout24.de/": {
        TradeDesk: { loadTime: 330, presence: 2 },
        "Facebook Conversion": { loadTime: 343, presence: 2 },
        Taboola: { loadTime: 345, presence: 8 },
        "LinkedIn Insights": { loadTime: 311, presence: 4 },
        "SalesForce DMP": { loadTime: 263, presence: 13 },
        "Tealium Tag Load": { loadTime: 550, presence: 4 },
        "Optimizely Active Event": { loadTime: 521, presence: 1 },
        "Nielsen DMP": { loadTime: 313, presence: 4 },
        "Tealium Loader": { loadTime: 271, presence: 1 },
        "Google Ads Remarketing": { loadTime: 278, presence: 3 },
        "TVSquared Tracker": { loadTime: 302, presence: 1 },
        "SalesForce DMP Consent": { loadTime: 272, presence: 1 },
        "Google Ad Manager (DFP)": { loadTime: 319, presence: 1 },
        AppNexus: { loadTime: 382, presence: 4 },
        "Google Universal Analytics": { loadTime: 269, presence: 2 },
        comScore: { loadTime: 352, presence: 2 },
        DrawBridge: { loadTime: 420, presence: 2 },
        "Optimizely Setup": { loadTime: 895, presence: 1 },
        "Bing Event Tracking": { loadTime: 281, presence: 1 },
        "Data Layer": { loadTime: 0, presence: 1 },
        "TVSquared Loader": { loadTime: 768, presence: 1 },
        "Facebook Events": { loadTime: 682, presence: 1 },
        "Taboola Loader": { loadTime: 604, presence: 1 },
        "Bing Ad Loader": { loadTime: 580, presence: 1 },
    },
    "https://atlas.immobilienscout24.de/eigentuemerbereich?cmp_id=10-04999&cmp_name=residential_myproperty&cmp_position=meinkontodropdown_eigentuemerbereich&cmp_creative=flyout_nav": {
        "Tealium Loader": { loadTime: 263, presence: 1 },
        "Optimizely Setup": { loadTime: 1082, presence: 1 },
        "Optimizely Active Event": { loadTime: 554, presence: 2 },
        "SalesForce DMP Consent": { loadTime: 274, presence: 1 },
        "LinkedIn Insights": { loadTime: 317, presence: 4 },
        "Google Ad Manager (DFP)": { loadTime: 321, presence: 1 },
        DrawBridge: { loadTime: 387, presence: 2 },
        "Tealium Tag Load": { loadTime: 414, presence: 4 },
        "Google Ads Remarketing": { loadTime: 282, presence: 5 },
        "SalesForce DMP": { loadTime: 266, presence: 13 },
        "Bing Ad Loader": { loadTime: 429, presence: 1 },
        Taboola: { loadTime: 332, presence: 8 },
        "TVSquared Loader": { loadTime: 578, presence: 1 },
        TradeDesk: { loadTime: 263, presence: 2 },
        comScore: { loadTime: 295, presence: 2 },
        AppNexus: { loadTime: 347, presence: 4 },
        "Google Universal Analytics": { loadTime: 260, presence: 2 },
        "Facebook Conversion": { loadTime: 339, presence: 2 },
        "Nielsen DMP": { loadTime: 318, presence: 4 },
        "Bing Event Tracking": { loadTime: 268, presence: 1 },
        "Taboola Loader": { loadTime: 430, presence: 1 },
        "Data Layer": { loadTime: 0, presence: 1 },
        "Facebook Events": { loadTime: 478, presence: 1 },
        "TVSquared Tracker": { loadTime: 302, presence: 1 },
    },
};
